### ISSUE TITLE
Feature: record levels

### ISSUE THREAD

**Issue by scottj97** [frosty656/frosty656.github.io#2]
I use this from my iPhone, and occasionally the phone will decide to reload it, resetting all building levels to 1. It's painful to have to go through and set them all to max level again.

I'm no web developer, but perhaps you could set a cookie or use local storage to record the levels and restore them on reload?

**Comment by frosty656** [comment]
This is something that I have looked into briefly. I had a half baked implementation that worked when running locally but did not work when running from GitHub pages. For sure something that I am looking to implement in the future.

**Comment by frosty656** [comment]
This has been added in the latest update!
