### ISSUE TITLE
Bug: belt items/min keeps resetting to 420

### ISSUE THREAD

**Issue by scottj97** [frosty656/frosty656.github.io#25]
Ever since #2 all my building levels stay where I've set them even when my iPhone decides to reload the page.

But for some reason the field for "Belt Items/Min" keeps getting reset to 420, instead of the 480 I'd set it to.

**Comment by frosty656** [comment]
Yup looks like when I added that feature I did not add it to the list of things to save! Updating now

**Comment by scottj97** [comment]
Excellent; thank you again for this awesome tool!

**Comment by frosty656** [comment]
Thank you for finding the issue and offering enhancements!
